[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm']

[phases.install]
cmds = [
  'corepack enable',
  'corepack prepare pnpm@10.18.1 --activate',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'pnpm start'

