module.exports = {
	arrowParens: 'avoid',
	bracketSpacing: true,
	embeddedLanguageFormatting: 'auto',
	endOfLine: 'auto',
	htmlWhitespaceSensitivity: 'css',
	insertPragma: false,
	jsxSingleQuote: true,
	plugins: ['prettier-plugin-tailwindcss'],
	printWidth: 80,
	proseWrap: 'preserve',
	quoteProps: 'as-needed',
	requirePragma: false,
	semi: false,
	singleQuote: true,
	tabWidth: 2,
	trailingComma: 'es5',
	useTabs: true,
	vueIndentScriptAndStyle: false,
}
