import '@/app/styles/global.css'
import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'
import localFont from 'next/font/local'

const ObraLetra = localFont({
	display: 'swap',
	src: './fonts/kc-obra-letra/kc-obra-letra-regular.ttf',
	variable: '--kc-obra-letra',
})

const ObraLetraBold = localFont({
	display: 'swap',
	src: './fonts/kc-obra-letra/kc-obra-letra-bold.ttf',
	variable: '--kc-obra-letra-bold',
})

const CardoRegular = localFont({
	display: 'swap',
	src: './fonts/cardo/cardo-regular.ttf',
	variable: '--cardo-regular',
})

const geistSans = Geist({
	subsets: ['latin'],
	variable: '--font-geist-sans',
})

const geistMono = Geist_Mono({
	subsets: ['latin'],
	variable: '--font-geist-mono',
})

// TODO: update metadata
export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='fr'>
			<body
				className={`${ObraLetra.variable} ${ObraLetraBold.variable} ${CardoRegular.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className='relative min-h-screen w-full'>
					{/* Main content wrapper */}
					{children}
				</div>
			</body>
		</html>
	)
}
