import '@/app/globals.css'

import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'
import localFont from 'next/font/local'

const ObraLetra = localFont({
	display: 'swap',
	src: '../../public/assets/Fonts/KCObraLetra/KCObraLetraRegular.ttf',
	variable: '--kc-obra-letra',
})

const ObraLetraBold = localFont({
	display: 'swap',
	src: '../../public/assets/Fonts/KCObraLetra/KCObraLetraBold.ttf',
	variable: '--kc-obra-letra-bold',
})

const geistSans = Geist({
	subsets: ['latin'],
	variable: '--font-geist-sans',
})

const geistMono = Geist_Mono({
	subsets: ['latin'],
	variable: '--font-geist-mono',
})

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${ObraLetra.variable} ${ObraLetraBold.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
