name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build
        env:
          PB_SERVER_URL: ${{ secrets.PB_SERVER_URL }}
          PB_USER_EMAIL: ${{ secrets.PB_USER_EMAIL }}
          PB_USER_PASSWORD: ${{ secrets.PB_USER_PASSWORD }}
          NEXT_PUBLIC_PB_SERVER_URL: ${{ secrets.PB_SERVER_URL }}

      - name: Build Docker image
        run: |
          docker build -t taverne-aventuriers:test \
            --build-arg PB_SERVER_URL=${{ secrets.PB_SERVER_URL }} \
            --build-arg PB_USER_EMAIL=${{ secrets.PB_USER_EMAIL }} \
            --build-arg PB_USER_PASSWORD=${{ secrets.PB_USER_PASSWORD }} \
            .