name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/taverne-aventuriers:latest
          build-args: |
            PB_SERVER_URL=${{ secrets.PB_SERVER_URL }}
            PB_USER_EMAIL=${{ secrets.PB_USER_EMAIL }}
            PB_USER_PASSWORD=${{ secrets.PB_USER_PASSWORD }}

      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' \
               --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'

      - name: Verify Deployment
        run: |
          echo "🎉 Deployed to production"
          echo "URL: ${{ secrets.PRODUCTION_URL }}"